dist: xenial   # required for Python >= 3.7
language: python
python:
  - "2.7"
  - "3.6"  
  - "3.7"  
  - "nightly"  
  - "pypy3.5"
install:
  - "pip install ."
  - "pip install -r src/tests/requirements.txt"
script:
  - sh -c 'cd src/tests && py.test'
    